### ISSUE TITLE
Optimizing the ops page

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq-dashboard#22]
When updating the Namesrv address, the width of the input element is fixed and the page display is not user-friendly.

![image](https://user-images.githubusercontent.com/18254437/134831374-1023fc84-ff50-4e15-9478-8c4114d065bd.png)

**Comment by yuz10** [comment]
@zhangjidi2016 
Now nameservers cant be updated, The content in the textbox is not sent to HTTP request 
![image](https://user-images.githubusercontent.com/14816818/134861010-6d9fcb15-5ba9-49bb-80ea-37c7e63d910e.png)

**Comment by zhangjidi2016** [comment]
After modifying the NamesrvAddr, you need to press Enter to make the modification into a new md-chip before clicking the Update button. The md-chips in Angular Material 1.1.0-rc2 does not support add-on-blur and can't convert directly to md-chip.If we refactor the front-end architecture later, consider upgrading to AngularJS and Angular Material  versions.

**Comment by StyleTang** [comment]
@yuz10 @zhangjidi2016 
I found there is a [issue](https://github.com/apache/rocketmq-externals/issues/720) related to this, it use `input` instead of `md-chips`, I should request @yuz10  to review this PR.
It is not a bug, but it seems md-chips is not easy to use.

By the way, I have send the RocketMQ Dashboard 1.0.0 release vote Email, could you have a look, thanks.
After 1.0.0 release, we can use the front-end architecture, and this user experience issue can be fixed

**Comment by yuz10** [comment]
OK, Sorry for the mistake.

**Comment by yuz10** [comment]
OK, Sorry for the mistake.
