### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:yarn (yarn build) on project rocketmq-dashboard: Failed to run task

### ISSUE THREAD

**Issue by lusheming** [apache/rocketmq-dashboard#35]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:yarn (yarn build) on project rocketmq-dashboard: Failed to run task

![image](https://user-images.githubusercontent.com/26221593/139366887-23bfbe82-3c9e-4209-a051-ae241957b1e0.png)
报这个错误

**Comment by StyleTang** [comment]
Sorry for the late reply, this issue may be caused by Windows does not have the `mv` command.

`rocketmq-dashboard/frontend/package.json` use the `mv` command to rename `index.html`

```json
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build && mv build/index.html build/app.html",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  }
```

Already [fix it](https://github.com/apache/rocketmq-dashboard/commit/d73d9b2793c40c7e8d88012e5ec5ee70c42f02d2), have a try again.

By the way, the rocketmq-dashboard 2.0.0 which will separate the frontend and backend is still in development, you can use the first release [rocketmq-dashboard-1.0.0](https://github.com/apache/rocketmq-dashboard/releases/tag/rocketmq-dashboard-1.0.0)

Hope it helps.
